* [2026-04-10 Fri]
Came up with a first wave for the fairies in group sp2 that seems pretty nice.

Now to come up with at least two more.

* [2026-04-08 Wed]
Been thinking and hacking on group sp2 for a while, but not satisfied with what's been happening so far (besides the decoration ring which is fine)

Also pasting in some chat logs on BHE about curved lasers for later reference:

williewillus (ping on response) [MOON], 
 — 
1:46 PM
considering finally implementing curved lasers (or any sort of mobile laser) into my engine...
does this sound about right?

    the "bullet" is the head of the laser and controls its motion as any other usual bullet would
    At some regular interval, the head leaves behind a node along its motion path. Nodes are kept as side data and are not bullets themselves
    Nodes despawn after some time based on the laser's configured length
    (optional) cancelling the middle of a laser splits it in two (removes the nodes from the original laser and creates a new head in charge of the new nodes)
    collision checks/grazing are just rectangle checks between each node


main questions are: how does rendering work? just drawing quads between each node? What frequency should I be creating nodes at? 
FuzzbearplushRole icon, Danmakufu
 — 
2:44 PM
I asked p much same thing recently in ZUNcode server, I haven't done it yet though
The frequency of new nodes should be every frame
I was thinking of having an allocated array of a specified length to place the nodes in, and every frame you shift the node data, and insert new node at the beginning
 [MOON], 
FuzzbearplushRole icon, Danmakufu
 — 
2:47 PM
Replying for ping
williewillus (ping on response) [MOON], 
 — 
2:47 PM
nice thanks
is the rendering as i described?
FuzzbearplushRole icon, Danmakufu
 — 
2:47 PM
Uhhh
I didn't really get the grasp of that yet
williewillus (ping on response) [MOON], 
 — 
2:48 PM
bc what i described seems sus but i cant think of anything better
FuzzbearplushRole icon, Danmakufu
 — 
2:48 PM
It should be quads between each nodes, but not squares/rectangles
Rough idea I came up with, ignore some randomly placed dots
Image
You could probably make it easier by making each of the "handles" originate from the node itself instead of in middle of nodes, but I feel like that would make hitbox stick out a little from the ends
williewillus (ping on response) [MOON], 
 — 
2:53 PM
cool thanks
williewillus (ping on response) [MOON], 
 — 
2:53 PM
re this iirc maingames use a linked list which makes sense to avoid shifting every frame
or even some sort of ring buffer if you impose a bound on how long a laser can be
FuzzbearplushRole icon, Danmakufu
 — 
2:58 PM
Maybe
You would probably have to iterate the nodes anyway so you can probably just throw shifting into that loop aswell
yuureikiRole icon, LuaSTG
 — 
5:04 PM
cheesers [2HU], Role icon, LuaSTG
 — 
5:54 PM
clean
 [MOON], 
Pickled Cow [MEW], Role icon, Godot
 — 
9:25 PM

    Yeah that's the fundamental of curvy lasers.


    Yes that is how I do it though I would consider the node to be core data tbh.


    The nodes should just be an array in the laser, every frame inheriting the one in front of it; this makes it so you only have to calculate values for one node each frame and you can just shuffle over the data.


    Cutting curvy lasers can be a bit tricky.  The correct way is to have data in the lasers about which node the collision and rendering should start and end at, this value starting at 0 and laser length at the start.

When the player its the middle of a laser, you create a complete duplicate of the laser and then update the two laser's start and end points to the node the collision occured at.
The reason we do this is so the trailing clone laser still follows the same path as the original laser; if we were to just create a new laser without this process its path would deviate. 
A small optimisation is the lead laser no longer needs its trail nodes that I haven't implemented myself yet.

    Rectangle works, just use whatever you have for regular lasers but between each node, infact my curvy lasers essentially are just holding lasers. I also though disable some of the head and tail nodes so you don't get randomly clipped; with lasers holding a float from [0, 1] on how much of the head/tail to disable (this is separate from the laser start and end I mentioned in 4). For logistical reasons these disabled nodes still have a bullet assigned to it in my implementation but you can definitely have that not be the case, I'm just fucking lazy.


Rendering: the rendering I do as a tri-strip with the sides being normal to the current node. The UVs of the mesh can just follow with x axis being node_id/max_node and y axis being 0 or 1 (or flip axis whatever doesn't matter). 
 [MOON], 
Pickled Cow [MEW], Role icon, Godot
 — 
9:25 PM
linked lists are kinda a trap here imo
if you leave it in the form of an array then you have opportunities to directly feed it into whatever rendering API directly instead of having to assemble it every single frame
not to mention the absolute cache miss nightmare linked lists are
Forwarded
Image
#lobby  •  9/19/21
here you can see what I mean by it deviating
with ZUN's implementaiton he just removes the head entirely instead of cutting it
but you can see how the new laser visually seems to curve too early
because the head position was moved to a middle node
williewillus (ping on response) [MOON], 
 — 
9:32 PM
super useful, thanks!
yeah im just gonna not deal with cutting for now
Pickled Cow [MEW], Role icon, Godot
 — 
9:33 PM
there were some crashing issues with mine so I did comment it out in mine too lol
I tried to be fancy and have the player cut out a radius
but there were some edgecases with 0 size lasers being created I couldn't be assed to deal with
another catch with cutting lasers is that you can't then have some script updating that laser anymore
the laser essentially needs to be self-managed
in a way that you can just simply copy the behaviour over
something akin to the AddPattern stuff in dnh
I adopted that pattern in mine because I really do like the set-and-forget model
 [MEW], 
Pickled Cow [MEW], Role icon, Godot
 — 
9:40 PM
also, by separating nodes from the actual bullets, you can cut some corners for performancy by only having a bullet every n nodes instead of every node
for high-radius curvature that can be a pretty free and unnoticeable way to make some optimisations
maybe not the optimisation goose to be chasing but it would be just leaving free cycles on the table

* [2026-03-18 Wed]
Spent the last couple days sprinting for Hazuki sp2 (and group non2 before that).

Very satisfied with group non2. Hazuki sp2 took a lot of tweaking and I think there's
still more to improve, but it's workable. Next will be Hazuki non2 and then group sp2.

I think it's about time I can try to set some deadlines. I'd like to be done with all the
boss patterns (at least a first pass) before Touhoufest. There's 12 attacks left to do
over 3 months, so that means at least 4 attacks per month, which means at least 1 per week
(on average). It'll be a good challenge.

* [2026-03-07 Sat]
Did some work a couple days ago to have the spellcircle not be terrible. I'm satisfied
with it.

Went on a pretty big diversion yesterday and today to profile memory usage and optimze it
(to the point of making a Chez Scheme PR to make cost-centers nameable).

Some ideas included unboxing/exploding a lot of temporary vec2/rectangle structs spammed
during render. However, after prototyping a lot of those ideas it didn't seem to actually
do much, so I'm shelving it for now. It was nice to go on the diversion, but I should
really be focusing on the actual content of the game.

I think next I'll probably work on group sp2 (something with the fairies) or the survival
(flower).

* [2026-03-02 Mon]
No dev work today (Sunday), but jotting something down quickly before i forget it.

For the spell circle following to not be terrible.

Essentially, track when the boss stops and starts moving. When she starts moving, store
the initial position and time. Then, continuous set the spell circle position to (lerp
initial-pos cur-pos (/ elapsed 30)). As the boss continuous to move, this will naturally
create the "trailing" effect we desire. Once the boss stops moving, the circle will
eventually catch up and then stop once the moving flag becomes false.

Not sure why it took me two whole ass years to think of this, but yeah. Should work.

* [2026-03-01 Sun]
Finally done with Aiko sp2.

Lots of adjustments, but I think I landed on something that seems hard at first but is
actually pretty simple.

Basically, when low on the screen, all the stars the ball spawns are aimed around the
player. The player should stay unfocused, ignore those stars, and concentrate on dodging
the stars from higher up on screen and hitting the ball.  And it's possible to shoot down
the spell even if you aren't trying very hard to hit Aiko with the ball, you just lose the
secret bonus.

Slotted the old Aiko non2 in as Aiko non1 and made the note bullets multicolored. This
sprite sheet has pretty awful note bullets though :/.

Nerfed Aiko sp1 by making it so the third wave always spawns nearer to the middle; from
experience this makes the spell quite a bit easier to dodge. Also, instead of randomly
picking the colors for each spiral, make them static so players can learn to dodge based
on the colors of the bullets.

Anyways, with this, all of Aiko's attacks are done now. Next, I'll probably return to
Hazuki sp2, or maybe Doremi sp2. The gimmick spells are always easier and more fun since I
can kinda let loose and do whatever.

* [2026-02-27 Fri]
Imported a new collision algorithm from the raylib-extras examples. It seems to work a lot
better.

Next immediate thing to implement is the ball bouncing off the player, then it's tweaking
and balancing as discussed earlier.

Also looked a bit into how macos/windows builds will work. For mac, seems like
https://github.com/quickemu-project/quickemu is the most convenient, and just running the
build steps in the VM and extracting the result. Can commit some scripts later to make sure
it's somewhat reproducible.

* [2026-02-20 Fri]
Hacked up the main loop for aiko sp2. It surprisingly works pretty well and fun to see
take shape.

Things to iron out:
- Collision is all sorts of wack. Should probably just hardcode a bunch of rectangles for
  the lasers and use the circle-rec function in geom.ss rather than doing a bunch of
  boundary check stuff. But then will run into tunneling issues. Seems complex -.-
- Timings and positions and stuff
- Smarter choice of what direction to shoot in
- Maybe some more decoration bullets

* [2026-02-18 Wed]

Only a bit of light work today but i think it's worth pausing briefly to figure out how
the enemy and ball control tasks will coordinate for aiko sp2.

Balls are transient as they can leave the playfield and despawn.

Enemy task will coordinate spawning the ball and respawning it if it leaves the field.

The ball control function itself is responsible only for its motion, nothing else.

We'll have a "signal" box like we've done previously to turn on and off the ball's motion.

Enemy task will go roughly like this:

- Go to ball (turn off its motion). If no ball, spawn it.
- Take ball to shooting spot
- play little "run up" animation and sfx
- "kick" ball, aka give it a direction and speed, unfreeze its motion
- wait a bit for it to bounce around, either hardcoded time cap or until speed goes below
  a certain point (former probably easier and can be hardcoded based on the bounds of the
  initial speed), or if the ball leaves the play field
- wait a bit, then repeat

Another thing to think about is how the ball will behave when colliding with the player.

Probably will need something like this
https://stackoverflow.com/questions/35211114/2d-elastic-ball-collision-physics but I have
a suspicion that we'll probably have to do quite a bit of tweaking because the player's
speed will always be pretty low compared to the ball.

* [2026-02-08 Sun]
(late night Saturday)
Redid Aiko non2. I think forcing the player to the bottom of the field should be the point
of the non instead of hinting at bouncy bullets, because the ball in sp2 works different
anyways (it won't kill the player). Meaning we have to explain it with some other hint in
the spell anyways.

I like the little moonlight-ray clone I ended up with. it's pretty easy, in line with most
final nons in extra stages being breathers.

The previous bullet pattern we can give to another nonspell, maybe aiko sp1 or girl's nons.

One thing I need to fix but it's too late at night: Damage-delegator bosses ignore
superarmor, as a result of the previous damage refactor.

Starting to feel the pain of the fan/circle builders having a big cliff between the paved
path (cb/fbshootenm and cb/fbshootez) and not (cb/fbshoot). For example, if i want to
customize the bullet type based on position in the fan/ring if have to drop to fbshoot and
instantly have to pay all the boilerplate. Wonder if spending time to hack up some
sequence utils/transducer stuff like clojure will be worth the time.

* [2026-02-04 Wed]
Hacked up Aiko non2. It's simple but serves the purpose of telling the player more bouncy
bullets are coming up ahead. As always, there's some balancing adjustments needed but the
core is sound.

When characters switch out, I programmed it so that the exiting character uses a subtask
and the incoming character does it in their spawn coroutine. I'm not sure why I had it
that way, but trying to move the exiting character' exit from a subtask to the main task
crashes. Didn't look into it further but logging here in case something comes up again.

Also, when programming boss attacks, I find it most useful to put everything into a
subtask gated by the keep-running function. If you do things in the context of the main
task then every kind of looping you have needs to check keep-running to make sure you're
not hanging around past when the enemy's health or time limit is depleted. It's just
easier to put everything into a subtask and have that check keep-running for you.

This might be a mismatch with the whole "attacks tail-call each other" paradigm, but I
think that design is still useful because it allows you to jump to specific phases and
msot importantly keep playing after that phase is done.

* [2026-01-31 Sat]
(late night)

Aiko sp1 is done but pretty unbalanced. I was fooling around with Hazuki sp2, which
originally was intending to be a CIV reference what with ghost/wisps attacking Hazuki and
getting a bonus for saving her, but after some thought I felt like it would kinda be
reflecting on her character in a negative light, so I've tabled the idea.

Instead, moving on to aiko sp2 which is the next best baked idea I have. Got the lasers
for the field setup, next is to set up the bouncing ball physics. Not sure yet whether i
want the shots to interact with the ball, because the fire rate here is too fast. Either
shots don't interact or we'd have to slow the fire rate down to hrtp speeds, or disable
autofire. idk.

Originally I had an idea as well to do some sort of "footrace" thing to tie in with Aiko's
running career in the light novels, but given this spell is right before the survival I
don't think a prolonged attack is appropriate, so the penalty shootout idea is what we're
going with. Need to research pong AI's and how they angle their shots, but honestly it's
not hard to rederive myself.

* [2026-01-12 Mon]
Just some quick noodling around with aiko sp1. I like where it's going; obviously it's
unbalanced and visually barebones, but I think the basic skeleton is quite serviceable.

* [2026-01-10 Sat]
(late night)

Loading up some spell backgrounds from a pattern book I bought a while back.

Spent a long time futzing about with Raylib's DrawTexturePro again, whose origin/rotation
arguments still confuse me to this day. I'm just going to ignore it and do things using the
GL matrix.

The pattern book has some circular patterns with a "background" color in the middle that's
obviously meant to become transparent when you use the pattern, but I tried some of them
out and they don't look too good when the stage background shows underneath. So I settled
on the ones that are mostly opaque.

At first I rendered the texture shrunk too small and was wondering why it looked
wrong. After enlarging, /then/ I got that nice maingame feel. Though you still want to
shrink a bit so that you get as much of the detail from the original texture as possible,
but not too much that the square corners of the texture start showing up as the texture
spins. I think what we landed on in the end looks alright.

* [2026-01-08 Thu]

- Added a filled circle hint particle
- Made spawn-particle call make-particle for you
- Some rough sketching of aiko sp1. Found a pretty major bug in the coro library, which is
  that sub-subtasks don't exit when their parent exits normally
  (i.e. without the parent's keep-running becoming false).
  Fixed that. Doesn't seem like anything in the stage is relying on it.

* [2025-12-31 Wed]
Going to try harder this upcoming year to write in the devlog every day I do any
development. Just some cleaning up today, adding in fireball bullets, and granularizing
the roadmap more.

* [2025-11-15 Sat]
How should the dialogue system work?

probably plain readable data in external file
something like:

((type . reimu) (text . "First line
second line"))
((type . doremi-surprised) (text . "Reply"))
"Plain string means same character and expression as previous"
((type . doremi-enter)) ;; dummy types interpreted specially by the code
((type . bossmusic))

see dialogue/main.dat for a sketch.


* [2025-11-06 Thu]
Basic replays exist but they're pretty buggy and there's no UI.
Main problems:

1. In the transition from gui to game, things can get wonky because technically a
   frame can be skipped or happen twice. This can be reproed by just trying to
   pause a replay during playback, it'll crash right when you unpause. Also
   pausing during a real run will cause the replay output stream to skip a frame.
2. More concerning bug is if a replay is restarted from the pause menu, it
   mysteriously desyncs, but only 1k-2k frames after. The beginning of the replay
   still works properly. This is the scariest case since it passes some of the
   sanity checks but not all, which means I'm leaking some sort of state across
   playback instances...but not sure what.
3. Not having UI for saving the replays and such makes testing annoying as I can
   only have one test replay at once and it gets blown away when I do a full run.
4. Still don't have a way to mark replays that "end early" via pause->save and quit.
   These just crash after the playback runs out of data to read.
   
I'll probably actually ignore the bugs for now and implement the UI parts first
just to make debugging less of a pain.

* [2025-11-04 Tue]
Some brief brainstorming/planning for replays. I tend to just go for it when
coding on this project but i think it's worth planning just a bit for this
so I don't have to do too much backtracking.

Replays will be plaintext (potentially with extra compression later but it will
be optional/layered on top s.t. plaintext ones are still loadable).
This makes it easy to debug when things go wrong.

It'll be line-based. Last line will be a score-entry record to carry the
score/timestamp/signature/clear state of the replay. Easy to reuse the existing
struct here. Last line to avoid having to copy everything after the replay ends.
When loading replays we'll read the entire thing into memory anyways, so

Each subsequent line will be a vector of the following fields

- frame number
- edge-pressed vkeys
- edge-released vkeys
- level-pressed vkeys
- (no edge pressed raw since no gameplay should ever read that)
- (optional) whether an unpause happened this frame and if so how long paused in realtime
- (optional) game-rng checkpoint state. should be verified at the beginning of the frame.
  - REQUIRED for frame 0
- (optional) END flag marking the end of the replay, for replays that quit out
  in the middle of the stage
  
The file should naturally be sorted by frame. We'll sort on load so that we can
naturally progress to the next entry without having to build a hashmap of
frame number -> entry.

We should write a line to the file each frame so we can at least attempt to have
failure recovery (?) though probably won't provide that as a feature.
But savvy people can edit the replay to salveage partial replays.

If there are no pressed or released keys and none of the optional fields are set,
then we can omit the record completely for that frame to save space.

* [2025-09-26 Fri]
Back from vacation. The entire stage portion is completely done. Assessing where we are
now, I think I want to work on the dialogue system next, then replays. So it'll be a bit
of infrastructure time instead of pattern work, but I'm keeping some brainstorming going
on in the background for when the time comes.

I probably won't have strict music syncing with the boss fight because it's really hard to
do if the music isn't designed with the fight in mind. The BGM will probably just be a
looped version of Half Point.

I also need to start practicing art again because I want to draw all the character
portraits myself. If I'm extra ambitious, maybe I'll even have different portraits for the
spell card cutins. This can proceed in parallel with working on the infra bits.

* [2025-08-23 Sat]
Pretty much all but one chapter of the stage patterns are in place.

Some replay brainstorming:

We'll have to first refactor input to introduce a layer of indirection: we need to capture
the current state of any level-triggered keys, as well as the list of all edge-triggered
key changes that happened in the frame. This needs to happen at the start of the frame and
produce a snapshot of the input state, and the handle-input function should operate solely
based on this snapshot.
This snapshot will also be used to write the input state for that frame of the replay.

(This might require another prerequisite refactor step to abstract away from the raw keys
and deal with what danmakufu calls the virtual keys (up down left right shoot bomb, etc.))

Then, playing replays is just setting the rng seed properly, then providing the snapshots
to handle-input from the replay file instead of the live input devices.

We can also save the rng state into the replay every X frames and compare it to the live
game-rng state to ensure we don't have any rng-based desyncs. Probably disabled in prod or
set to a pretty high interval (every 10 seconds?).

* [2025-05-11 Sun]
Some chapter 1 hacking, but I also took some time to figure out the Windows build process.
It's actually super simple, everything basically just works. The build.ss script runs
directly under WINE and with raylib.dll in the working directory the game starts and runs
just as expected.

Distribution for Windows will just be zipping up the Chez Scheme install folder alongside
thdawn.boot and raylib.dll, and maybe a bat script to start the game.

The statically-linked/dependency-bundled distribution for Linux will be similar, if I choose
to make one.

* [2025-05-10 Sat]
Now mostly at a point where I should just be banging out the stage patterns, though I've
instead been faffing about, mostly with splines and how I can more cleanly represent enemy
movement that isn't purely aligned with the cardinal/ordinal axes.

* [2025-03-08 Sat]
Oops, didn't update the devlog in forever. To be fair, not much has been happening either.

Slowly been chipping away at some boss infra stuff. Most of it is in place now, except
for rendering the spell name and the health bar.

Still unclear how I'm going to represent health in the context of having multiple
nons/spells, but it'll be an important thing to figure out before I continue on.

Once I finish those three things and lasers, it'll /finally/ be time to actually start
designing the stage danmaku.

* [2024-11-23 Sat]
Started this devlog to help track progress and motivate myself. A bit late since a lot of
the core infra of the game has already been laid down, but late is better than never.

Added support in the coroutine system for generic pre- and post-hooks that are run before
and after each time a coroutine resumes. This will be used for running general bookkeeping
needed for all enemy types. Slightly worried if I can keep a good separation between
the bookkeeping and the main task logic, but won't dwell on it until it becomes a problem.

Sorted bullets before render. Just uses the allocating vector-sort instead of a dedicated
buffer, since GC's generally don't like old-to-young gen pointers, and there's no optimized
primitive to blit one vector to another. It seems to perform just fine.

Also went on a sidequest to finally read up about how errors and conditions work in
R6RS/Chez. I was thinking it'd be nice to have exception handlers around certain parts of
the code like each coroutine resume for better interactive dev (if it's possible to
recover from such errors, I'm not sure how flexible Chez is here).

Turns out the condition system is kinda complex because it has additional polymorphism
behavior beyond which R6RS records specify. Chez provides the continuation for lots of
condition types, but you can't use it to implement CL style restarts, presumably because
the point at which the continuation is captured is always "too late"?

For example, this:
#+BEGIN_SRC scheme
(define (p m) (display m) (newline))

(guard (x [else
		   (p "before")
		   ((condition-continuation x) 1) ;; try to resume from the (error) call
		   (p "after")])
  (let ([f (error 'who "what")])
	(p "out")
	f))

(p "done")
#+END_SRC
does not print "after" nor "out".

So any error handling I do won't provide a friendlier repl experience, though I could
presumably fail-safe and discard the erroring enemy to prevent a program crash.

Next: Want to actually start implementing the movement animation system that I've been
procastinating about the last 3 weeks. At least the infra-side tracking of the delta
motion if not the actual rendering.

